version: "3.8"
services:
  web:
    image: ghcr.io/redcloud442/mithril:prod
    env_file:
      - .env.production

    deploy:
      mode: replicated
      replicas: 3
      update_config:
        order: start-first
      labels:
        - shepherd.enable=true
        - shepherd.auth.config=ghcr.io
    ports:
      - "8080:8080"
  server:
    image: ghcr.io/redcloud442/mithril:prod-server
    environment:
      SUPABASE_URL: /run/secrets/supabaseUrl
      SUPABASE_ANON_KEY: /run/secrets/anonKey
      SUPABASE_SERVICE_ROLE_KEY: /run/secrets/serviceRoleKey
      PORT: 3000
      DATABASE_URL: /run/secrets/databaseUrl
      DIRECT_URL: /run/secrets/directUrl
      UPSTASH_REDIS_REST_URL: /run/secrets/redisUrl
      UPSTASH_REDIS_REST_TOKEN: /run/secrets/redisToken
    secrets:
      - databaseUrl
      - directUrl
      - supabaseUrl
      - anonKey
      - serviceRoleKey
      - redisUrl
      - redisToken
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        order: start-first
      labels:
        - shepherd.enable=true
        - shepherd.auth.config=ghcr.io
    ports:
      - "3000:3000"
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    networks:
      - public
    secrets:
      - tunnelKey
    environment:
      - TUNNEL_TOKEN=/run/secrets/tunnelKey
    deploy:
      replicas: 2

  shepherd:
    image: containrrr/shepherd:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - shepherd.enable=true
        - shepherd.auth.config=ghcr.io
    environment:
      REGISTRIES_FILE: /run/secrets/shepherd-registries-auth
      SHEPHERD_LOG_LEVEL: info
      SHEPHERD_POLL_INTERVAL: 60
      IMAGE_AUTO_CLEANUP: "true"
      ROLLBACK_ON_FAILURE: "true"
      IGNORELIST_SERVICES: shepherd cloudflared
      UPDATE_OPTIONS: "--update-delay=30s"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - shepherd-registries-auth

secrets:
  databaseUrl:
    external: true
  directUrl:
    external: true
  supabaseUrl:
    external: true
  anonKey:
    external: true
  serviceRoleKey:
    external: true
  baseUrl:
    external: true
  tunnelKey:
    external: true
  redisUrl:
    external: true
  redisToken:
    external: true
  shepherd-registries-auth:
    external: true

networks:
  public:
    external: true
